### ISSUE TITLE
Different behaviour on fault clearing

### ISSUE THREAD

**Issue by martinscripts** [bertrtam00/wecc_iec_model_comparison#13]
after fault clearing the models have different dynamic behaviour: 

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/7cb84fed-39bb-4df4-b0d7-60bd3b4baf87)

# WECC
- very slow integral part (steady state error takes long to disappear)
- asymptotic

# IEC
- faster integral part
- oscillations

**Comment by adriguir** [comment]
You are looking at the outputs of the electrical controls here, isn't it?
When looking to the generator outputs - corresponding variables iqRefPu for WECC, iqCmdPu but after the frame rotation in IEC - the plots have a more similar shape, even if they still have some differences.

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/38657764/234a936b-8f0e-400b-b4ee-9607bb8029ad)

I suppose the FRT detection could be the origin of the difference and the overshooting of the IEC compared to WECC (FRT released based on Ufiltered in IEC instead of Uraw in WECC). 

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/38657764/e05c4dc4-cd6d-41d0-bf16-9f293c9aa9f6)


Any reason to look at the electrical part specifically?

**Comment by adriguir** [comment]
I will try to decrease the filtering for FRT in IEC and see if it gets closer to the WECC with this modification.
Not the good explanation, it has for sure an influence but doesn't make the behaviors closer...

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/38657764/dd833309-10f6-4969-9edf-01a51d44d8c4)

**Comment by martinscripts** [comment]
thanks. 
I was investigating the electrical controls because of other issues and then compared the currend commands there.
it's more transparaent there and structually they are so similar that also in the electrical system should behave almost identically.
